### ISSUE TITLE
bash: sonarwhal: command not found

### ISSUE THREAD

**Issue by kshyju** [sonarwhal/sonarwhal#1009]
I am following the [Create A Custom Rule Step-By-Step](https://sonarwhal.com/docs/contributor-guide/guides/create-custom-rule/) tutorial and i created a new rule using the CLI.

When i am doing this specific part

> > 
> And now run `sonarwhal https://sonarwhal.com` in the terminal and wait for the scan to complete.
> 

I get a message, 

`bash: sonarwhal: command not found`

I am running this command in VS Code terminal

```
My-MacBook-Pro:sonarwhal me$ ls
CODE_OF_CONDUCT.md      appveyor.yml            node_modules            scripts                                         tsconfig.json
LICENSE.txt             cdp.pid                 package.json            tsconfig.json                                   yarn.lock
README.md               coverage                packages                yarn.lock
My-MacBook-Pro:sonarwhal me$ sonarwhal https://sonarwhal.com
bash: sonarwhal: command not found
My-MacBook-Pro:sonarwhal me$
```

I tried running it from the `packages` directory as well, but same result!

I do have node and yarn installed (I ran the tests before creating my custom rule).

**Comment by kshyju** [comment]
Thanks! But I thought this repo contains the the source of the sonarwhal package as well(`packages\sonarwhal\src`). I was hoping to use that version so that i can run & debug the source code as necessary as well.

**Comment by molant** [comment]
> But I thought this repo contains the the source of the sonarwhal package as well

Yes, that's correct. If you want to do that you can do:

1. Clone the repo
1. `yarn install`
1. `yarn new:rule`

That will create a new "official" rule under `packages` and what I mentioned in my previous comment will still apply and unlock you.

I'm pinging @sarvaje in case you need more help with this. @alrra is traveling today and I'm at an event so we won't have connectivity all time.

**Comment by kshyju** [comment]
Thanks @alrra @molant @sarvaje . Really appreciate the help.
