### ISSUE TITLE
Move "how to use this rule" after the "further reading" section

### ISSUE THREAD

**Issue by molant** [sonarwhal/sonarwhal#1018]
The how to use this rule is mostly a copy paste in all rules and while it provides useful information, it's not as important as to why the user should care (especially if they are using the online version).

Per https://github.com/sonarwhal/sonarwhal/pull/1015#pullrequestreview-114320857 we should move that section towards the end.

**Comment by alrra** [comment]
> Move "how to use this rule" after the "further reading" section

Or right before "further reading".

**Comment by sarvaje** [comment]
I'm going to do this, what's the final position, before or after "further reading"? :)

**Comment by molant** [comment]
Don't have a strong opinion so you decide 😛

**Comment by sarvaje** [comment]
>Don't have a strong opinion so you decide 😛

Before then hehehe. I prefer the further reading to be the last thing in the documentation.
