### ISSUE TITLE
Support define rules via CLI (would ignore .sonarwhalrc rules)

### ISSUE THREAD

**Issue by laukstein** [sonarwhal/sonarwhal#1020]
Allow

```
sonarwhal https://example.com --rules http-cache manifest-is-valid ssllabs
```

that would skip .sonarwhalrc rules configuration and apply only rules **http-cache**, **manifest-is-valid** and **ssllabs** with its default configuration (`rule: "error"`).

The benefit: running all defined rules in .sonarwhalrc may be very slow and, while working on website fixes for specific role, it would be easier, quicker and "directly to target" to revalidate by single/few rule/s defined in CLI.
Since it might be complicated to defined custom config per rule in CLI (maybe like `sonarwhal https://example.com --rules ssllabs:["error", {"grade": "A+"}]`; also applying .sonarwhalrc rule config from  would be wrong here since actually wanted to ignore it here), I suggest currently apply the rules default configuration.

**Comment by molant** [comment]
> I personally don't think we should do it. It will just complicate things with no real benefit.

I actually think it will be nice to have this feature. Many times I've wanted to just know if a website was using `sri` or how it was doing on `http-compression`. Instead of modifying the `.sonarwhalrc` file on my home folder for those specific use cases I could just have done what @laukstein proposes :)

> I suggest currently apply the rules default configuration.

Agree, this should be a quick shortcut and shouldn't try to get parity with the config file

@kshyju did something similar for the formatters in #1017. The only difference with your proposal is that we used `,` to separate the formatter names.

I don't think this should be very difficult to implement.

@sonarwhal/contributors any one else wants to give their opinion?

**Comment by sarvaje** [comment]
I like the idea too. Sometimes we just need to test one or two specific rules and this can help us.

**Comment by alrra** [comment]
> this should be a quick shortcut and shouldn't try to get parity with the config file

I'm fine with that! :+1:

**Comment by kshyju** [comment]
Yes. I can work on this.

**Comment by kshyju** [comment]
How about 
`sonarwhal https://example.com --rules http-cache, html-checker`

_(spaces added for readability here)_

Same as the formatters option, it will accept a comma separated list of rules and use that.

I am thinking about setting the severity as "warning" by default so the CLI is clean and simple.  Should we make it sophisticated to accept the severity levels for each rule as well ? 

Something like ?
`sonarwhal https://example.com --rules http-cache:warning, html-checker:error, sri:warning`

Or
`sonarwhal https://example.com --rules ?http-cache:warning, !html-checker, ?sri`

**Comment by laukstein** [comment]
@kshyju, know that configuration might be more complicated then you mention, like `["error", {"grade": "A+"}]`, `["warning", {"html": {"brotli": false}}]`. I don't like option with `?` and `!`.
Is comma separator important here or is unnecessary?

Make sure that `--rules` works fine together with `--formatters`.

**Comment by molant** [comment]
I think we should keep it as simple as possible. No custom configuration and no severity. I don't have any strong opinion between error or warning for it.

The following looks fine to me:

`sonarwhal https://example.com --rules http-cache,html-checker`

**Comment by laukstein** [comment]
@alrra could you release sonarwhal with this?

**Comment by alrra** [comment]
@laukstein Done!
