### ISSUE TITLE
Configuration schema is not valid when using array format to specify rules

### ISSUE THREAD

**Issue by kshyju** [sonarwhal/sonarwhal#1025]
As per the [documentation](https://sonarwhal.com/docs/user-guide/concepts/rules), we can configure rules as an array like this
```
{
    "rules": [
        "rule1:warning"
    ]
}
```

But this does not work! When running sonarwhal, i get an error saying the config schema is not valid

```
Shyjus-MacBook-Pro:sonarwhal shyju$ yarn sonarwhal https://news.ycombinator.com -f summary
yarn run v1.6.0
$ node dist/src/bin/sonarwhal https://news.ycombinator.com -f summary
Configuration schema is not valid
Error: Couldn't find any valid configuration
    at Function.fromConfig (/Users/shyju/Documents/Dev/GitHub/sonarwhal/packages/sonarwhal/dist/src/lib/config.js:188:19)
    at exports.analyze (/Users/shyju/Documents/Dev/GitHub/sonarwhal/packages/sonarwhal/dist/src/lib/cli/analyze.js:123:45)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
    at Function.Module.runMain (module.js:692:11)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Shyjus-MacBook-Pro:sonarwhal shyju$


```
I tried switching the `type` from `object` to `array` in the `config-schema.json` file, but that did not help!

## Environment

* __`sonarwhal` version:__  v1.7.0
* __`Node.js` version:__ v9.10.1
* __`npm` version:__5.8.0

### My sonarwhal config

```
{
    "connector": {
        "name": "chrome",
        "options": {
            "waitFor": 1000
        }
    },
    "formatters": ["summary"],
    "parsers": [],
    "rulesTimeout": 120000,
    "rules": [
        "amp-validator:warning",
        "sri:warning"
    ]
}

```

This also does not work

    "rules": [
        "?amp-validator",
        "?sri"
    ]

**Comment by alrra** [comment]
> Configuration schema is not valid

[`config-schema`](https://github.com/sonarwhal/sonarwhal/blob/36b80b21f9f955448f7fbe692a6f797f0e6d4b9b/packages/sonarwhal/src/lib/config/config-schema.json) needs to be updated.

---

Another questions related to this, do we want to still support the shorthands? I haven't seen anyone using it.

**Comment by molant** [comment]
>  Do we want to still support the shorthands?

For @kshyju work on #1029 it would have been handy. Also we haven't promote them a lot so that could be the reason.

I personally like the shorthand version `amp-validator:warning`. I think we should try to fix the scenario, maybe adding a "preprocessor" right after reading the JSON file that converts it to the standard format? This way we don't have to complicate the config-schema.
