### ISSUE TITLE
Rule to check static assets are minified

### ISSUE THREAD

**Issue by kshyju** [sonarwhal/sonarwhal#1032]
I think there should be a rule which checks the static assets(primarily js and css) coming from server as minified. If not, this is a perf recommendation for the user.

**Comment by molant** [comment]
Any idea on how to approach this reliably?

Some things we could check for:
* Lines are really long (we will need a threshold for that)
* Not too many lines (what would be good number?)
* No comments?  The problem with this is that sometimes you need to add licenses
* ??

**Comment by molant** [comment]
OK, I've assigned the task to you for now 😊
