### ISSUE TITLE
Can't install on WSL/Debian 9.4, Win10 1803 (April update)

### ISSUE THREAD

**Issue by amankkg** [sonarwhal/sonarwhal#1050]
Tried with `sudo`, via `nvm` or changing `npm`'s default directory - all the same error.

## Environment

* __`OS`:__ Win10 1803 (April update) build 17134.48, WSL Debian 9.4
* __`sonarwhal` version:__ 1.8.1 to be installed
* __`Node.js` version:__ v8.11.1, v10.1.0
* __`npm` version:__ 5.6.0, 6.0.1

## `sonarwhal` configuration

<details>
<summary>sonarwhal’s configuration</summary>

```js



```

</details>

## URL for which `sonarwhal` failed

* __URL:__

## Output

Please include the raw output generated by `sonarwhal`, or if possible,
the raw output from running `sonarwhal` in debug mode: `sonarwhal --debug <URL>`.

<details>
<summary>sonarwhal’s raw output</summary>

```text
root@xps9360:~# sudo npm i -g --engine-strict sonarwhal
/usr/bin/sonarwhal -> /usr/lib/node_modules/sonarwhal/dist/src/bin/sonarwhal.js

> canvas-prebuilt@1.6.5-prerelease.1 install /usr/lib/node_modules/sonarwhal/node_modules/canvas-prebuilt
> node-pre-gyp install

node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/sonarwhal/node_modules/canvas-prebuilt/canvas/build'
node-pre-gyp ERR! System Linux 4.4.0-17134-Microsoft
node-pre-gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/sonarwhal/node_modules/.bin/node-pre-gyp" "install"
node-pre-gyp ERR! cwd /usr/lib/node_modules/sonarwhal/node_modules/canvas-prebuilt
node-pre-gyp ERR! node -v v10.1.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
EACCES: permission denied, mkdir '/usr/lib/node_modules/sonarwhal/node_modules/canvas-prebuilt/canvas/build'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @sonarwhal/connector-edge@1.0.0 (node_modules/sonarwhal/node_modules/@sonarwhal/connector-edge):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @sonarwhal/connector-edge@1.0.0: wanted {"os":"win32","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 (node_modules/sonarwhal/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas-prebuilt@1.6.5-prerelease.1 install: `node-pre-gyp install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas-prebuilt@1.6.5-prerelease.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-05-10T20_27_57_451Z-debug.log
```
</details>

**Comment by molant** [comment]
Does [this tip](https://sonarwhal.com/docs/user-guide/#permission-issues-during-installation) solve the issue?

**Comment by amankkg** [comment]
@molant 
I'll check it later and update the status...

**Comment by amankkg** [comment]
Tried changing `npm` directory. Tried using `nvm`. No luck.
Also, same issue with `nvm/node v8.11.1, npm@5.6.0`.
Seems like WSL issue. 😞

**Comment by molant** [comment]
What version of Windows and WSL are you using? Is it the April update? An insider? Ubuntu?

**Comment by amankkg** [comment]
version 1803
build 17134.48
wsl - Debian 9.4

**Comment by sarvaje** [comment]
`nvm` it is working for me in debian and ubuntu.

OS build: 17672 (insider)
wsl - debian and ubuntu

**Comment by molant** [comment]
@sarvaje can you download a VM from https://edge.ms and test with the stable release?

**Comment by sarvaje** [comment]
sure thing!

**Comment by sarvaje** [comment]
I have downlaod a VM with the latest stable release and it works following [these](https://sonarwhal.com/docs/user-guide/#permission-issues-during-installation) instructions.

**Comment by amankkg** [comment]
Wiped Debian app from app settings and installed using NVM - now it's OK.
Yet another difference - first time I was running wsl as a root and for now as regular user.
