### ISSUE TITLE
`getRuleName` doesn't work for packages with multiple rules.

### ISSUE THREAD

**Issue by sarvaje** [sonarwhal/sonarwhal#1054]
In these cases, it returns just the name of the package, but not the name of the rule you want to test.

**Comment by kshyju** [comment]
What is it supposed to return when a package has more than one rules in it ? How does it know what to return ?

**Comment by sarvaje** [comment]
For example, in the case of `rule-typescript-config`, `getRuleName` should return something like:
`typescript-config/consistent-casing` or `typescript-config/import-helpers`.

**Comment by kshyju** [comment]
>  should return something like:
> typescript-config/consistent-casing **or** typescript-config/import-helpers.

**Or** ?
Does that mean, any rule present in the package directory ? What is the value of doing that ? What if i want the rule name for a test i am writing for the second/third rule ?

**Comment by sarvaje** [comment]
Those were just a couple of examples.

What I mean is that `getRuleName` should return, for multi rules packages, `{packageName}/{ruleName}`

**Comment by kshyju** [comment]
Going back to my original question.

What is it supposed to return when a package has more than one rules in it ? How does it know which rule name to return ? The only way to solve the problem is to take the optional rule name when calling the method ? 

`const ruleName = getRuleName(__dirname,"is-installed");`

**Comment by molant** [comment]
In multi rule packages the convention so far is to name the file test the same as the rule we are testing.

**Comment by alrra** [comment]
Done in https://github.com/sonarwhal/sonarwhal/commit/232564d4e80b163208b0295faacaa98e53a07da4.
