### ISSUE TITLE
List what packages are not compatible with the sonarwhal version

### ISSUE THREAD

**Issue by molant** [sonarwhal/sonarwhal#1063]
The following message could be improved by listing the packages that are causing problems.

![image](https://user-images.githubusercontent.com/606594/40025702-625a5a8e-5787-11e8-9059-0b74648bf19a.png)

**Comment by molant** [comment]
@sarvaje assigning it to you for now. If I start working on this I'll let you know.

**Comment by sarvaje** [comment]
ok!

**Comment by sarvaje** [comment]
@molant I'm going to start with this

**Comment by molant** [comment]
👍
