### ISSUE TITLE
Make interaction with CLI more frictionless

### ISSUE THREAD

**Issue by alrra** [sonarwhal/sonarwhal#1095]
- [ ] Make CLI by default not ask any questions

   Users are sometimes confused by the questions asked by the initial wizard, so we should make the first interaction as frictional as possible and don't ask any questions at all and just default to using the `web-recommended` configuration. However, we should display a message linking to a documentation page that informs them how things can be customized/configured.

- [ ] Make CLI run even if a valid configuration is not found

  Here, again, we should display a message informing the user that a valid configuration is not found, and we are using a default one.

- [ ] Other?

**Comment by sarvaje** [comment]
>  Make CLI run even if a valid configuration is not found
Here, again, we should display a message informing the user that a valid configuration is not found, and we are using a default one.

Are we sure we want to do that? IMO, if you have a wrong config we should fail or ask if they want to create a new config or run the default one.

**Comment by alrra** [comment]
>  IMO, if you have a wrong config we should fail or ask if they want to create a new config or run the default one.

Well, the idea was to ask less questions. However, I'm open to different opinions.

@sonarwhal/core ?

**Comment by sarvaje** [comment]
>Well, the idea was to ask less questions. However, I'm open to different opinions.
@sonarwhal/core ?

Ok, meantime I'm going to work on the first point.

**Comment by molant** [comment]
I think we should have something like:

> Couldn't find any valid configuration. Want to use the default one? Learn more about the default config in https://something

We still have the problem with packages that are outdated or missing though. I think it will be nice to have a diagram flow so we can decide what is best on each case. It should probably start with "is sonarwhal installed globally? Yes/No"

**Comment by sarvaje** [comment]
@molant That's for the point 1, 2 or both?

**Comment by molant** [comment]
For the whole CLI. We need to capture somewhere what happens since the moment someone types `sonarwhal https://example.com` and what could happen

**Comment by sarvaje** [comment]
This is the diagram with the two points in the description + what we already have. @sonarwhal/core do you thing something should be different?
![image](https://user-images.githubusercontent.com/1581288/40519142-e0d6267a-5f72-11e8-9584-ec784759e362.png)

**Comment by sarvaje** [comment]
I have just updated the diagram.

![image](https://user-images.githubusercontent.com/1581288/40561505-5dcfc7d6-6012-11e8-9593-5dbea6a71789.png)

**Comment by sarvaje** [comment]
Task to do to match the diagram:
- [ ] Run `web-recommended` configuration if no configuration file is found.
- [ ] Ask to use `web-recommended` if the configuration file is not valid.
- [ ] Choose formaters has to ask for one or more formatters
- [ ] Change how to detect if sonarwhal is installed locally or not.
