### ISSUE TITLE
Add rule to check for dead links

### ISSUE THREAD

**Issue by antross** [sonarwhal/sonarwhal#1107]
Especially in areas like documentation this can happen as content gets reorganized, but can be difficult to spot. A rule which loads links listed on a page and flags if any of them returns a `404` could help.

**Comment by alrra** [comment]
@antross See https://github.com/sonarwhal/sonarwhal/pull/1104.

**Comment by antross** [comment]
Thanks. Awesome to see there's already a PR in progress!
