### ISSUE TITLE
new rule wizard can't know if it is an "official" rule or not

### ISSUE THREAD

**Issue by sarvaje** [sonarwhal/sonarwhal#1129]
we were using the package name, but it was removed here 2a980a8cec9fb16c19c24ddfc91de64232a7b556

we need to recover the package name or think in another way to recognize if we are creating an 'official' rule or not.

**Comment by molant** [comment]
The only purpose of that package name was to help us exacty with that and I don't think it's worth investing time trying to find another way when this is just a one liner.

@alrra?
