### ISSUE TITLE
Add rule(s) for HTTP compression

### ISSUE THREAD

**Issue by alrra** [sonarwhal/sonarwhal#12]
## gzip

1. Check is something is served compressed using `gzip`:

    Make a request  with the `Accept-Encoding: "gzip"` header, then verify if the response is served with the `Content-Encoding: "gzip"` header and the body of the response starts with [`1f 8b`](https://tools.ietf.org/html/rfc1952#page-5).

2. What should be compressed with `gzip`:

    | File type | Commonly used<br>file extension(s) |Commonly used<br>media types(s) |
    |:---|:---|:---|
    | Atom | `.atom` | `application/atom+xml` | 
    | App Cache Manifest | `.appcache` | `text/cache-manifest` |
    | BMP | `.bmp` | `image/bmp` |
    | CSS | `.css` | `text/css` | 
    |  [Cursors Images](https://en.wikipedia.org/wiki/ICO_(file_format)) | `.cur` | `image/x-icon`<br>`image/vnd.microsoft.icon`|
    | Embedded OpenType font | `.eot` |  `application/vnd.ms-fontobject` |
    | [Favicon](https://en.wikipedia.org/wiki/Favicon) | `.ico` | `image/x-icon`<br>`image/vnd.microsoft.icon`|
    | HTML | `.html`<br>`.htm`<br>... | `text/html`<br>`application/xhtml+xml` |
    | [HTML Components](https://en.wikipedia.org/wiki/HTML_Components) | `.htc` | `text/x-component` |
    | JavaScript | `.js` | `application/javascript`<br>`text/javascript` | 
    | JSON | `.json`<br>... | `application/json`<br>`application/<something>+json`|
    | OpenType  font |  `.otf` | `font/opentype` |
    | RDF | `.rdf` | `application/rdf+xml` |
    | RSS | `.rss` | `application/rss+xml` |
    | Source Maps | `.map` | `application/json` |
    | SVG | `.svg` | `image/svg+xml` |
    | TrueType font | `.ttc`<br>`.ttf` | `application/x-font-ttf` |
    | TXT | `.txt` | `text/plain` |
    | vCard | `.vcard`<br>`vcf` | `text/vcard` |
    | VTT | `.vtt` | `text/vtt` |
    | XML | `.xml`<br>... | `application/xml`<br>`text/xml`<br>`application/<something>+xml` |
    | Web App Manifest | `.webmanifest`<br>`.json` | `application/manifest+json` |

    Notes:
     
      * Under 1K things should not necessarily be compressed.
      * `WOFF` fonts should not be compressed (see: https://github.com/h5bp/server-configs-apache/issues/42).
      * `SVGZ` should be served with the `Accept-Encoding: "gzip"` header as they are compressed by default.
       

## Zopfli

1. Check is something is served compressed using `Zopfli`:

    Same as with `gzip`, just that we need to [detect `Zopfli`](https://github.com/MicrosoftEdge/Sonar/issues/1).

2. What should be compressed with `Zopfli`:
   
    Same as with `gzip`.

    Note(s):
   
      * We will need to a check if `WOFF` fonts use `Zopfli` compression internally.

## Brotli

1. Check is something is served compressed using `Brotli`.

    Make a request  with the `Accept-Encoding: "br"` header, then verify if the response is served with the `Content-Encoding: "br"` header ([no magic numbers?](https://github.com/google/brotli/issues/298#issuecomment-172549140)).

   Note: `Brotli` compressed responses should be [served only over HTTPS](https://medium.com/@yoavweiss/well-the-technical-reason-for-brotli-being-https-only-is-that-otherwise-there-s-a-very-high-508f15f0ad95).

2. What should be compressed with `Brotli`:
  
    Same as with `gzip`.

--- 

Note: This is just a starting point, we will probably split this into more specific issues / rules.

**Comment by molant** [comment]
This has a dependency on #164 to work cross collector.

**Comment by AndrewCraswell** [comment]
+1 for this. Especially the highlighting of Brotli compression!

**Comment by molant** [comment]
@alrra is working hard on this
