### ISSUE TITLE
Add rule(s) to check for usage of `P3P` 

### ISSUE THREAD

**Issue by alrra** [sonarwhal/sonarwhal#140]
- [ ] Check if the header is sent.
- [ ] Check if the link tag is used.

---

P3P was only supported in Internet Explorer, and is obsolete in [_Microsoft Edge and all modes of Internet Explorer 11 for Windows 10_](https://msdn.microsoft.com/en-us/library/mt146424.aspx):

> Support for P3P 1.0 has been removed in Windows 10 and will have minimal ongoing servicing for previous versions of Windows. Recommended practice is to avoid deploying P3P privacy policies on your site.

---

See also:

* https://www.w3.org/TR/P3P/
* http://www.cylab.cmu.edu/research/techreports/2010/tr_cylab10014.html

**Comment by frvge** [comment]
Note that my PR only checks for the header. It does NOT check for the meta/link elements. Those don't work either way.
