### ISSUE TITLE
Add ability to test the local file scenario

### ISSUE THREAD

**Issue by alrra** [sonarwhal/sonarwhal#212]

**Comment by alrra** [comment]
> * Replace `worksWithLocalFiles` with `scope` or something similar. The scope will be `local`, `site`, `any` (or some better names).

:+1:

> Any headers related rules will only be site. 

Some rules check the headers and also something else (e.g.: a meta tag), they may be `any`.

**Comment by molant** [comment]
> Some rules check the headers and also something else (e.g.: a meta tag), they may be `any`.

Depending on the rule. `highest-available-document-mode` I believe should be `site` because of the way we check things (we require the `header` by default). In any case, we will review each individual rule and decide if it's not obvious.

**Comment by alrra** [comment]
>  we will review each individual rule and decide if it's not obvious.

:+1:

**Comment by sarvaje** [comment]
> Based on the above, if the user selects a rule that cannot run on local, we should print a warning (maybe the user is just doing some tests?) but not initialize the rule

What about if the user selects another connector and has a `local` rule selected?

**Comment by sarvaje** [comment]
> We will need to add a new parser for HTML to keep sending traverse::XXX and element:XXX events from the local connector, hopefully reusing the jsdom one so there isn't any duplication (I believe there's a comment about this somewhere but couldn't find it).

I think we just need a subset of the functionality from the jsdom connector. i.e: we don't need to load the resources.

Am I wrong?

**Comment by molant** [comment]
> What about if the user selects another connector and has a `local` rule selected?

Same, print a warning.

> we don't need to load the resources.

That's correct.

**Comment by alrra** [comment]
Closing as this issue is no longer relevant.

See also: https://github.com/sonarwhal/sonarwhal/commit/f4536396d3177c969eee023a6598aa1ba5e0cefe.
