### ISSUE TITLE
Add rule to check subresource integrity

### ISSUE THREAD

**Issue by alrra** [sonarwhal/sonarwhal#26]
- [x] `<script>` or `<link>` elements don't have the `integrity` attribute 
- [x] the content of the `<script>` or `<link>` elements doesn’t match the associated `integrity` value 
- [x] other checks (TODO: read the spec)

----

See also:

* https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity
* Spec: https://w3c.github.io/webappsec-subresource-integrity/

**Comment by molant** [comment]
* Spec: https://w3c.github.io/webappsec-subresource-integrity/#does-response-match-metadatalist
