### ISSUE TITLE
Refactor worksWithLocalFiles config for rules

### ISSUE THREAD

**Issue by molant** [sonarwhal/sonarwhal#263]
Right now rules have a property `worksWithLocalFiles` that if set to `false` will not execute if the resource uses the `file://` protocol.
I think we should refactor and abstract the protocol. Right now there are a few rules that will not work if the resource is a data url ([`content-type`](https://github.com/MicrosoftEdge/Sonar/pull/256/files#diff-f5c90d62f5b0a966680f6be21272169cR180),[`disallow-headers`](https://github.com/MicrosoftEdge/Sonar/pull/256/files#diff-4000a9dd39bc1bb8fb8c984d9f81feebR47), etc.).
I think it should be something like `doesntApplyTo: ['file:', 'data:']` or a better name.

**Comment by alrra** [comment]
Closing as [we moved away from `worksWithLocalFiles`](https://github.com/sonarwhal/sonarwhal/commit/f4536396d317).
