### ISSUE TITLE
[Proposal] Improve rules configuration with include/exclude

### ISSUE THREAD

**Issue by molant** [sonarwhal/sonarwhal#343]
This is the remaining work for the original scope of #283.

A configuration file should look like:
```js
{
    "rules": [
        "rule1",        // Default to "error"
        "rule2:warn",   // Switch to warn
        "rule3:off",    // Quickly disable a rule
        ["rule4", {
            exclude: /.*\.foo\.com/.*/
        }],
        ["rule5", {
            include: [/.*\.domain1\.com/.*/],
            exclude: [/.*\.foo\.com/.*/]
        }],
        ["rule6", {
            include: ['*.domain1.com/**'] // Simple glob
        }],
        { // Additional rules for a specific domain
          include: ['*.foo.com/**'],
          rules: [
            'rule7',
            'rule8'
          ]
        }
    ],
    include: [ // Only run rules for the following URLs
      '*.ebay.com'
    ],
    exclude: [ // Don't run rules for any of the following URLs
      'tracking.ebay.com'
    ]
}
```

So rules should allow the options include/exclude for domains.

This is related to #287 and will make `ignoredUrls` obsolete.

@austinkelleher I don't think there is another issue tracking this.

**Comment by alrra** [comment]
> include: [ // Only run rules for the following URLs

`include` is not a good name for that (`restrictTo` comes to mind, but I don't like that either).

---

Maybe we can have the `"include"` functionality basically baked into `exclude`, e.g.:

```
exclude: [
   '*',  // exclude everything
   ''!*.ebay.com'' // except *.ebay.com
]
```

See also: https://github.com/isaacs/node-glob#comments-and-negation

**Comment by patrick-steele-idem** [comment]
Here are some decisions by other libraries that give precedent:

- [rollup uses `include`/`exclude`](https://github.com/rollup/rollup-plugin-commonjs)
- [webpack uses `include`/`exclude`](https://webpack.github.io/docs/configuration.html)
- [babel uses `ignore`](https://babeljs.io/docs/usage/api/)

Personally, I prefer `include`+`exclude` for matching URLs since it feels intuitive. I think that negation for `exclude` makes things more confusing.

**Comment by alrra** [comment]
_Updated [my previous comment](https://github.com/sonarwhal/sonar/issues/343#issuecomment-312796649)._

**Comment by molant** [comment]
My vote is for include/exclude:

> I prefer include+exclude for matching URLs since it feels intuitive. I think that negation for exclude makes things more confusing.

Yes, I've wasted too much time in the past trying to know what the problem was because of this.

**Comment by austinkelleher** [comment]
My vote is also for `include`/`exclude`

**Comment by molant** [comment]
@AustinKelleher let's go for include / exclude then!

**Comment by molant** [comment]
This seems related to #766

Idea is to have a whitelist of urls and then restrict the rules for those domains via `ignoredUrls`. I think the current approach is easier to implement than adding new properties to each rule.

Closing feel free to reopen in case you disagree.
