### ISSUE TITLE
Provide more information when running `--init`

### ISSUE THREAD

**Issue by alrra** [sonarwhal/sonarwhal#361]
From https://github.com/sonarwhal/sonar/pull/358#discussion_r125529863:

> We could improve already the question here and briefly explain what a connector is. Maybe add a description for each one? Something similar to:
> > What connector do you want to load the content of the website?
> > * cdp (you will need to have chrome installed)
> > * jsdom (will use jsdom, no additional installation required)

----

See also: https://github.com/sonarwhal/sonar/issues/326#issue-238851829

**Comment by molant** [comment]
We should use the shortlinks of https://github.com/sonarwhal/sonarwhal.com/issues/185 for this.
