### ISSUE TITLE
Warn if Byte-Order Mark is present?

### ISSUE THREAD

**Issue by tigt** [sonarwhal/sonarwhal#371]
In #328, @alrra researched some gotchas with including the BOM at the front of UTF-8 documents:

>* Some tools/build processes will strip the BOM character (just look how used tools like [this one](https://www.npmjs.com/package/strip-bom) is), which will mean a lot of figuring out where the problem is.
>* Most people probably don't know about BOM, and will be confused about the weird character their editor **may** show.
>* [+ Other (old?) issues](https://www.w3.org/International/questions/qa-byte-order-mark#problems).

Should Sonar warn if it detects the BOM? Or would an informational note be more suitable?

**Comment by molant** [comment]
I would create a new rule for this. Not sure how we should implement this cross connector. I believe CDP will strip out the BOM directly and I'm not sure we can access the raw body for a text response so we might have to use fetchContent and use the same headers.

@sarvaje you've been working with the connectors recently. Thoughts about getting the bytes?

**Comment by alrra** [comment]
> I would create a new rule for this

[Yes, that was the idea](https://github.com/sonarwhal/sonar/issues/328#issuecomment-313903507). Also it should not only check HTML documents, but other types of text files.

**Comment by molant** [comment]
I've created PR #919 for this.
