### ISSUE TITLE
Inconsistent default sonar config

### ISSUE THREAD

**Issue by qzhou1607** [sonarwhal/sonarwhal#472]
Not sure if this is a bug or a feature: The `.sonarrc` in the sonar repository is different from the default sonar config generated by running `--init`. Should we make them the same? @sonarwhal/contributors

**Comment by molant** [comment]
Maybe in the future?
Right now we are modifying it quite a few testing things and it is only used when scanning a site directly while coding. In any case, let's wait to see what the other people think.

**Comment by alrra** [comment]
@qzhou1607 Maybe point out the differences?

**Comment by qzhou1607** [comment]
@alrra You are right. The differences include:
When using `--init` default:
* All the recommended rules are set as `error`. 
* No `loadCompleteRetryInterval` or `maxLoadWaitTime` options are set

**Comment by molant** [comment]
> All the recommended rules are set as error.

The reason why they are warning in the project is that `npm run site https://SITE.com` will output all the `This script failed but it is most likely not an issue with npm` that takes a lot of space. I think we should keep them as warnings.

> No loadCompleteRetryInterval or maxLoadWaitTime options are set

We should look into having some of them. I'm changing how the wait times work on `chrome` in my work on #471 so I would wait before anything in here.

**Comment by alrra** [comment]
@molant Can this be closed?

**Comment by molant** [comment]
I think so. I'm not worried about inconsistencies because we are just using that file while manually testing.
