### ISSUE TITLE
Further improve `release` script

### ISSUE THREAD

**Issue by alrra** [sonarwhal/sonarwhal#476]
Change script to:

- [x] Handle case when `snyk-snapshot.json` isn't updated.
- [x] Make it work properly on Windows (see: #564)
- [x] `npm` 2FA
- [ ] Update the `User-Agent` string for `requester.ts` with latest Chrome and current sonar version (see https://github.com/sonarwhal/sonar/pull/629#discussion_r148959656)
- [x] Automatically update `performance-budget/connections.ini` (see: https://github.com/sonarwhal/sonarwhal/pull/798/files#r166410722)
- [x] Rollback Git(Hub) changes (latest commit(s), tags, etc. if something goes wrong)
- [x] Other?

**Comment by molant** [comment]
Did you do the snyk one?

**Comment by alrra** [comment]
> Did you do the snyk one?

Yes.

**Comment by alrra** [comment]
- [ ] Handle case when `snyk-snapshot.json` isn't updated.

**Comment by molant** [comment]
* [X] Better error output
* [X] Switch all `shelljs.exec` to `async`

**Comment by alrra** [comment]
- [ ] Make it work properly on Windows (see: #564)

**Comment by molant** [comment]
I believe the script fails on Windows if there are more than 1 change. At least that's what I think was happening to me the other day.

**Comment by alrra** [comment]
- [ ] npm 2FA

**Comment by alrra** [comment]
- [ ] Automatically update `performance-budget/connections.ini` (see: https://github.com/sonarwhal/sonarwhal/pull/798/files#r166410722)

**Comment by molant** [comment]
* [ ] Rollback Git(Hub) changes (latest commit(s), tags, etc. if something goes wrong
