### ISSUE TITLE
Make `sonar` only recommend the connectors that actually work on the user's platform

### ISSUE THREAD

**Issue by alrra** [sonarwhal/sonarwhal#517]
E.g.: Currently the `chrome` connector doesn't work on Windows Subsystem for Linux (WSL).

**Comment by molant** [comment]
It actually is supported but some changes need to happen on [`chrome-launcher`](https://github.com/GoogleChrome/chrome-launcher/issues/26) to detect it. In any case, we should also be smart and detect what browsers the user has installed.

**Comment by molant** [comment]
Now that we are using configuration packages (and `web-recommended` uses `jsdom` by default) and `edge` is an optional dependency installed only if possible, this issue seems obsolete.

I'm closing it but feel free to reopen it if you disagree @alrra
