### ISSUE TITLE
Allow testing pages that require authentication / login

### ISSUE THREAD

**Issue by Graham42** [sonarwhal/sonarwhal#628]
Feature request: Allow testing pages that require authentication / login.

If this is already possible, I couldn't find anything in the docs.

**Comment by molant** [comment]
I think the easiest way to enable this before we allow automation would be to:

* Authenticate into that page using the same browser that sonar is going to use (one that supports the debugging protocol)
* Add a new parameter to the connector config to not start a new session and pass it to the launcher (somewhere [around here](https://github.com/sonarwhal/sonar/blob/ca02a33311e9dc3c17721bd0b916337b5d3617a9/src/lib/connectors/chrome/chrome-launcher.ts#L108))

We might have to disable the empty cache path in this case but should probably be fine for this scenario.

@sonarwhal/core what do you think?

**Comment by molant** [comment]
@Graham42 I've done a PR to Chrome Launcher with this feature in https://github.com/GoogleChrome/chrome-launcher/pull/48

Hopefully it will get merged and published soon and can continue the work in here.

**Comment by galak06** [comment]
is it possible to give an example to login (username/password)

**Comment by molant** [comment]
@galak06 feature isn't finished. Once it is the documentation will say how to use it and the limitations.

**Comment by NogeekIT** [comment]
@molant did you manage to test pages that requires authentication ?

**Comment by molant** [comment]
I'm still waiting on having https://github.com/GoogleChrome/chrome-launcher/pull/48 merged.

Hopefully after Thanksgiving 😊

**Comment by ricardogaldino** [comment]
Hi, is that correct? It did not work for me.

{
    "browserslist": [],
    "connector": {
        "name": "chrome",
        **"options": {
            "defaultProfile": true
        }**
    },
    "formatters": [
        "codeframe"
    ],
