### ISSUE TITLE
Add examples on how to configure servers in order to pass the rules

### ISSUE THREAD

**Issue by Mexikaner9** [sonarwhal/sonarwhal#649]
can you show me an example for a .htaccess which passes your scanner rules?
this doesnt pass your rules

```apache
 Header set X-UA-Compatible "IE=Edge,chrome=1"
 Header set X-Frame-Options "SAMEORIGIN"
 Header set X-XSS-Protection "1; mode=block"
 Header set X-Content-Type-Options: "nosniff"
 Header set Strict-Transport-Security "max-age=31536000; includeSubDomains;"
 Header set Referrer-Policy "strict-origin-when-cross-origin"
```

**Comment by alrra** [comment]
Yes, I think it would be great to have examples on how to configure servers in general, not just Apache.

**Comment by alrra** [comment]
...and/or link to projects that do a good job at that.

**Comment by Mexikaner9** [comment]
Yes, it would be great to have small examples on how to configure servers in general, not just Apache, and/or link to projects that do a good job at that.

**Comment by alrra** [comment]
- [X] Add Apache configs (done in https://github.com/sonarwhal/sonarwhal/commit/afc468d7541754ff6d5992fc106514a093ce68eb)
- [ ] Add IIS configs
- [ ] Add NGINX configs
