### ISSUE TITLE
Update Safari related rules once Safari has support for the web app manifest

### ISSUE THREAD

**Issue by alrra** [sonarwhal/sonarwhal#661]
Recently, [work started to implement the web app manifest spec in WebKit](https://lists.webkit.org/pipermail/webkit-dev/2017-October/029694.html).

Once that is done, we should update the Safari related rules (e.g.: `apple-touch-icons`) to suggest using the manifest where it makes sense.

**Comment by poshaughnessy** [comment]
This would be good! One of my first impressions when trying out the tool was getting a PWA "error" for not including `apple-touch-icons`. I feel like that's not really a PWA error that a developer must address, when Apple have an older, proprietary system and don't really support PWAs in general yet ;-) (A warning would be good though!)

**Comment by alrra** [comment]
> Update: Oh - so this errors by default when running it online at https://sonarwhal.com, but when running it locally, it's set to warning by default? (I've got "apple-touch-icons": "warning" in my .sonarwhalrc...)

@poshaughnessy The online scanner is currently in a preview mode and does not provide all the functionalities of the CLI as we didn't have the time to implement some of the things there such as allowing configurations.

From https://sonarwhal.com/scanner/:

> sonarwhal's online version is currently in preview. Results and reliability might vary. **Nellie has chosen a set of rules for you**, but in the future you will be able to decide which ones you want.

Because of that, the scanner currently comes with a custom configuration, but we plan to change that in the near future. Sorry about the confusion. 

Is there any way you think we can make that more clear on the site?

**Comment by alrra** [comment]
It's now marked as [`In Development`](https://webkit.org/status/#specification-web-app-manifest) on their status page. 🎉

**Comment by alrra** [comment]
https://medium.com/@firt/pwas-are-coming-to-ios-11-3-cupertino-we-have-a-problem-2ff49fd7d6ea

**Comment by alrra** [comment]
> https://medium.com/@firt/pwas-are-coming-to-ios-11-3-cupertino-we-have-a-problem-2ff49fd7d6ea

Related to the `apple-touch-icon`, it seems that in the beta versions of Safari that have support for the web app manifest, [they are still using it, instead of the icons defined in the manifest](https://medium.com/@firt/pwas-are-coming-to-ios-11-3-cupertino-we-have-a-problem-2ff49fd7d6ea#e5af).

**Comment by alrra** [comment]
From https://developer.apple.com/library/content/releasenotes/General/WhatsNewInSafari/Articles/Safari_11_1.html#//apple_ref/doc/uid/TP40014305-CH14-SW6:

> New in Safari 11.1—Web App Manifest
>
>   Added support for websites declaring how web apps behave and appear when using “Add to Home Screen”.

**Comment by alrra** [comment]
I'm going to update the documentation and close this issue as, for the time being, there isn't anything to be done about this.

Once Safari changes its behavior we can reopen / revisit this issue, and update the rule.
