### ISSUE TITLE
Thank you for building this tool! 💓

### ISSUE THREAD

**Issue by mlcdf** [sonarwhal/sonarwhal#663]
Hi there

I just want to say thank you for making this handy tool. It made me learn that the Wep App Manifest file extension should be `.webmanifest` which then led me to make my first contribution to MDN (!!!) by updating the code snippet with the proper extension. 

💓

**Comment by alrra** [comment]
> I just want to say thank you for making this handy tool.

@mlcdf Thank you, we sincerely appreciate the kind words!

> which then led me to make my first contribution to MDN (!!!) 

Woohoo, thank you for doing that! 💜
