### ISSUE TITLE
Remove `X-UA-Compatible` requirement, since IE is depreciated

### ISSUE THREAD

**Issue by laukstein** [sonarwhal/sonarwhal#666]
I propose to remove `X-UA-Compatible` requirement, since IE is depreciated. Especially when based on https://sonarwhal.com/docs/user-guide/rules/highest-available-document-mode/ `X-UA-Compatible: ie=edge` is relevant only for IE 8/9/10. Today none must be using those browsers, even Microsoft tries hard to replace it with Edge.

Is related to #139.

**Comment by alrra** [comment]
> I propose to remove X-UA-Compatible requirement, since IE is depreciated. 

If you [give some context to `sonarwhal`](https://sonarwhal.com/docs/user-guide/#browserconfiguration), the rule will actually suggest not sending the HTTP header and removing the meta tag.

**Comment by alrra** [comment]
@laukstein If you are referring to the [online scanner](https://sonarwhal.com/scanner), it doesn't currently allow things to be configuration at the moment, but we are planing to change that in the near future.

**Comment by laukstein** [comment]
@alrra `X-UA-Compatible` must be avoided by default, it is depreciated. Please reopen this issue.

**Comment by molant** [comment]
@laukstein [`X-UA-Compatible` takes into account the browser configuration the user sets](https://sonarwhal.com/docs/user-guide/rules/highest-available-document-mode/#cantherulebeconfigured) so it will tell the user to remove it or add it depending on that support matrix.

The online scanner uses the default [`browserslist`](https://www.npmjs.com/package/browserslist) which is

**Comment by molant** [comment]
@laukstein let's discuss this over https://github.com/sonarwhal/sonarwhal.com/issues/309
We don't have any plans on changing how the rule works, but we can change how the online scanner behaves.

Thanks!

**Comment by laukstein** [comment]
@molant http://browserl.ist/?q=%3E+1%25%2C+last+2+versions%2C+Firefox+ESR
returns old browsers even with 0% usage (less than 1%), also IE10 with usage 0.15% . Perhaps you expect more than 1% usage and you need to use another condition, or it is a bug in https://github.com/ai/browserslist ?
