### ISSUE TITLE
user-scalable produces an error even if its set to "yes"

### ISSUE THREAD

**Issue by jsmad** [sonarwhal/sonarwhal#667]
By default, an error is produced when user-scalable appears in the meta tag headers: Meta tag has disallowed property: 'user-scalable' 

This error appears even when user-scalable is set to "yes", like below:

```html
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
```

To be more compatible with existing HTML code and overall specifications, it would be better if this error only appeared when user-scalable was set to "no".

Thank you.

**Comment by alrra** [comment]
> To be more compatible with existing HTML code and overall specifications, it would be better if this error only appeared when user-scalable was set to "no".

@jsmad:

From https://sonarwhal.com/docs/user-guide/rules/meta-viewport/#whyisthisimportant:

> `user-scalable`, `maximum-scale`, and `minimum-scale` properties should not be used
> 
> ... these properties are now ignored by some some mobile browser such as [Safari for iOS 10+](https://webkit.org/blog/7367/new-interaction-behaviors-in-ios-10/)
