### ISSUE TITLE
Add connector-edge as an optional dependency

### ISSUE THREAD

**Issue by molant** [sonarwhal/sonarwhal#671]
Now that the [connector-edge](https://npmjs.com/packages/@sonarwhal/connector-edge) is published and working with RS2 and RS3 we should look into adding it as an optional dependency that will get installed if we detect a compatible Windows 10 version.

Things to do:
* [x] Add it as an optional dependency
* [x] Update the wizard to show it if it appears
* [ ] Update the documentation to mention it and list the limitations

**Comment by alrra** [comment]
Reopen this as there is one last thing to be done:

> -[ ] Update the documentation to mention it and list the limitations
