### ISSUE TITLE
CloudFlare's mandatory __cfduid cookie should not penalize site

### ISSUE THREAD

**Issue by laukstein** [sonarwhal/sonarwhal#681]
Fallow Mozilla steps https://github.com/mozilla/http-observatory/issues/121 and skip validation fort CloudFlare's `__cfduid` cookie

![grabilla em7172](https://user-images.githubusercontent.com/183966/33393385-b6e2f8c6-d547-11e7-94cf-f37613d95bfc.png)

**Comment by alrra** [comment]
Before discussing if we allow or not `__cfduid`, as @molant pointed out to me, it seems we also have a parsing issue, hence the _"Invalid date format in 'expires'..."_

----

Example of the cookie that fails:

```text
set-cookie: __cfduid=d36daf5c1330234711b94f1e340502c191512063473; expires=Fri, 30-Nov-18 17:37:53 GMT; path=/; domain=.laukstein.com; HttpOnly; Secure
````

**Comment by molant** [comment]
The rule is actually failing because the format is not the correct one and not for the reasons explained in `http-observartory` so closing this issue.
