### ISSUE TITLE
Make errors more descriptive/provide descriptions

### ISSUE THREAD

**Issue by staabm** [sonarwhal/sonarwhal#682]
I just scanned a webproject we made and I can see a lot of errors like

![grafik](https://user-images.githubusercontent.com/120441/33420461-f1e8e7fc-d5ae-11e7-984f-5ffa72361907.png)

this makes me think of why is the `x-xss-protection header not needed`? in the first place its a security header and its not obvious why I should not use them (or maybe its a more complex context here which I dont know about and needs explanation?)

**Comment by alrra** [comment]
@staabm For ever error, there is a documentation link that should provide all the information related to that specific test (e.g.: for [`x-xss-protection header not needed`](https://sonarwhal.com/docs/user-guide/rules/no-html-only-headers/))

![](https://user-images.githubusercontent.com/1223565/33432961-c452553c-d58e-11e7-9202-bd679df99f96.png)

**Comment by alrra** [comment]
@staabm Do you think this is not obvious enough? If you have any ideas/suggestion on how we can improve it, can you [open an issue in the site repository](https://github.com/sonarwhal/sonarwhal.com/issues/new)? Thanks!
