### ISSUE TITLE
errors for well-known external services

### ISSUE THREAD

**Issue by staabm** [sonarwhal/sonarwhal#683]
I just scanned a webproject we made and I can see a lot of errors like

![grafik](https://user-images.githubusercontent.com/120441/33420461-f1e8e7fc-d5ae-11e7-984f-5ffa72361907.png)

this is a url/resource/service which I cannot change/influence. Would it make sense to have some kind of blacklist/whitelist in sonarwhal which makes this errors/warnings hidden in the first place, as I cannot change those anyway?

The above mentioned list could contain hosts/domains/... which are used on a big portion of websites and be curated in a separate sonarwhal/* repos. It would contain things like facebook.com google.com googleadservices.com etc. - so mention resources which are linked from a lot/most of sites.

**Comment by alrra** [comment]
> Would it make sense to have some kind of blacklist/whitelist in sonarwhal which makes this errors/warnings hidden in the first place, as I cannot change those anyway?

@staabm Using the CLI, you can configure [`sonarwhal` to ignore certain domains](https://sonarwhal.com/docs/user-guide/#ignoringdomains), such as the ones you don't have control over. However, with the [online scanner](https://sonarwhal.com/scanner/), since [it's currently in preview, it doesn't allow configurations](https://user-images.githubusercontent.com/1223565/33432516-1bd656de-d58d-11e7-95e2-390a658366be.png), but we plan to change that in the near future.

**Comment by molant** [comment]
We should probably ignore some of these urls automatically in the online scanner.
Maybe we should open an issue in the sonarwhal.com project and start collecting them?

**Comment by alrra** [comment]
> We should probably ignore some of these urls automatically in the online scanner.

Until we allow configurations in the online scanner, maybe? But, in general I disagree, people should know the problems with their third parties, and once they acknowledge them, decide if they want to ignore them or not (or just change the third party provider).

Also, if we do such a thing in the online scanner we need to make it perfectly clear to our users what is happening (so they don't think everything is fine, when that isn't the case). There is also the issue of why are we ignoring some URLs and not others, etc. Maybe our time is better spent on just making the scanner allow configurations?
