### ISSUE TITLE
[docs] Issue with 'Require `Content-Type` HTTP response header with appropriate value'

### ISSUE THREAD

**Issue by liquidlightuk** [sonarwhal/sonarwhal#692]
https://sonarwhal.com/docs/user-guide/rules/content-type/index.html

The default sonarwhal settings require javascript assets to be served using the "text/javascript" content-type and do not accept "application/javascript" as a valid value. 

My understanding is that RFC4329 (https://www.ietf.org/rfc/rfc4329.txt) made "text/javascript" obsolete and "application/javascript" is now the correct content-type. 

Could you please explain the rational behind this decision?

**Comment by alrra** [comment]
> Could you please explain the rational behind this decision?

@liquidlightuk See: https://github.com/sonarwhal/sonarwhal/issues/568#issuecomment-339945844.
