### ISSUE TITLE
`manifest-file-extension` parsing extension improperly

### ISSUE THREAD

**Issue by willfarrell** [sonarwhal/sonarwhal#698]
Source:
```bash
<link rel="manifest" href="/.well-known/favicons/manifest.webmanifest">
```

Scan:
```bash
Error    The file extension should be 'webmanifest' (not 'well-known/favicons/manifest')  manifest-file-extension
```

Expect it to pass, clearly `well-known/favicons/manifest` is not the file extension. I'm guessing the logic assumes there could be only one `.` in the path (pseudo code: `url.split('.')[1]`) instead of parsing from the end (`url.substr(-12)`), or using a url parsing lib (`url.parse(url).extension`).

## Environment
```bash
$ sonarwhal -v
v0.17.0
$ node -v
v8.8.0
$ npm -v
5.6.0
```

## `sonarwhal` configuration
all defaults

## URL for which `sonarwhal` failed

`https://registration.redcross.ca`

## Output

```bash
Error    The file extension should be 'webmanifest' (not 'well-known/favicons/manifest')  manifest-file-extension
```

https://github.com/sonarwhal/sonarwhal/issues/32
@alrra

**Comment by alrra** [comment]
@willfarrell Good catch!
