### ISSUE TITLE
Check if `strict-transport-security` rule takes into consideration preloaded TLDs

### ISSUE THREAD

**Issue by alrra** [sonarwhal/sonarwhal#699]
From https://textslashplain.com/2017/12/05/strict-transport-security-for-dev/:

> Chrome 63, shipping to the stable channel in the coming days, things have changed. Chrome has added .dev to the HSTS Preload list (along with the .foo, .page, .app, and .chrome TLDs)

---

See also: https://cs.chromium.org/chromium/src/net/http/transport_security_state_static.json?maxsize=9259190&l=278-286

**Comment by alrra** [comment]
From https://textslashplain.com/2017/12/05/strict-transport-security-for-dev/:

> Chrome 63, shipping to the stable channel in the coming days, things have changed. Chrome has added .dev to the HSTS Preload list (along with the .foo, .page, .app, and .chrome TLDs)

---

See also: https://cs.chromium.org/chromium/src/net/http/transport_security_state_static.json?maxsize=9259190&l=278-286

**Comment by molant** [comment]
Duplicate of #555
