### ISSUE TITLE
text/javascript vs. application/javascript

### ISSUE THREAD

**Issue by MarDiehl** [sonarwhal/sonarwhal#704]
I get the following message
'content-type' header should have media type 'text/javascript' (not 'application/javascript')

even though it seems that  'application/javascript' is preferred over 'text/javascript'.
See https://stackoverflow.com/questions/189850/what-is-the-javascript-mime-type-for-the-type-attribute-of-a-script-tag and references therein.

**Comment by alrra** [comment]
@MarDiehl See: #568.
