### ISSUE TITLE
Allow CLI to be run without .sonarwhalrc in current directory

### ISSUE THREAD

**Issue by poshaughnessy** [sonarwhal/sonarwhal#718]
Proposal: Given that the recommended use of the CLI is to point to a URL (rather than a local project), I would suggest we do not need to pollute the current directory with a `.sonarwhalrc` file.

How about...

1. If no `.sonarwhalrc` found in the current directory, look for `.sonarwhalrc` in user's home directory.
2. If no `.sonarwhalrc` found in user's home directory either, proceed with default configuration? (With an appropriate warning / note?). This would have the added benefit of reducing a necessary step (`sonarwhal init`) for first time users to try out the CLI.

(This may be related to #713?)

**Comment by alrra** [comment]
> I would suggest we do not need to pollute the current directory with a .sonarwhalrc file.
>
> If no .sonarwhalrc found in the current directory, look for .sonarwhalrc in user's home directory.

I personally agree that we should do that.

(I don't remember why we didn't do it that way in the first place 🤔)

> If no .sonarwhalrc found in user's home directory either, proceed with default configuration? (With an appropriate warning / note?).

As long as we make it clear (with an appropriate warning/note as you specified), I'm personally ok with it.

---

@sonarwhal/core Thoughts?

**Comment by alrra** [comment]
@poshaughnessy, @diekus, @torgo 

I was discussing this issue with @molant, and we think this can be a good first issue to solve that will also allow you to better understand how `sonarwhal` works.

Do any of you want to take this issue? We can help you along the way!

**Comment by poshaughnessy** [comment]
@alrra Sorry for the delay. If it's not too late, yes, let's give this a try! I'll see how far I get and hopefully can put in an initial PR for review and feedback :)

**Comment by alrra** [comment]
> If it's not too late, yes, let's give this a try!

Go for it, and don't hesitate to let us know if we can help!

**Comment by molant** [comment]
@poshaughnessy we've separated everything into packages now so if you want to give this a try let us know. Otherwise we will probably take care of this in the next few days.
There have been some changes in the projects structure so make sure to check the contributor guide (PR for those changes is https://github.com/sonarwhal/sonarwhal/pull/827 in case @alrra doesn't get to merge it before you read this).
