### ISSUE TITLE
Update `no-disallowed-headers` rule to allow `Server` header

### ISSUE THREAD

**Issue by alrra** [sonarwhal/sonarwhal#747]
For some servers (e.g.: [Apache](https://bz.apache.org/bugzilla/show_bug.cgi?id=40026)), the `Server` header cannot be removed without, for example, [installing an external module](https://superuser.com/questions/286805/how-to-remove-server-header-from-the-http-response-with-apache).

However, if we allow the `Server` we should still limit what information it can contain, e.g.:

* ❌  `Server: Apache/2.2.27 (Unix) mod_ssl/2.2.27 OpenSSL/1.0.1e-fips mod_bwlimited/1.4`
* ✅ `Server: Apache`

---

<details>
 <summary>HTTP Archive data on the usage of Server header values</summary>
 
* [Looking into the HTTP Archive data](https://www.igvita.com/2013/06/20/http-archive-bigquery-web-performance-answers/), in the last run, the top 100 most used `Server` headers values where:

  | | Number of requests | `Server` HTTP header value |
  |---:|---:|:---|
  | 1 | 7566576 | nginx |
  | 2 | 7482347 |  |
  | 3 | 5510024 | apache |
  | 4 | 2423646 | cloudflare-nginx |
  | 5 | 2404686 | sffe |
  | 6 | 1837824 | cafe |
  | 7 | 1442077 | cloudflare |
  | 8 | 1225752 | microsoft-iis/8.5 |
  | 9 | 1151821 | golfe2 |
  | 10 | 1122041 | amazons3 |
  | 11 | 992319 | microsoft-iis/7.5 |
  | 12 | 565495 | esf |
  | 13 | 535930 | netdna-cache/2.2 |
  | 14 | 531256 | nginx/1.12.2 |
  | 15 | 518236 | nginx/1.10.2 |
  | 16 | 510275 | litespeed |
  | 17 | 417270 | apache-coyote/1.1 |
  | 18 | 401882 | nginx/1.8.1 |
  | 19 | 372595 | apache/2.2.15 (centos) |
  | 20 | 321146 | nginx/1.12.0 |
  | 21 | 317403 | http server (unknown) |
  | 22 | 315105 | nginx/1.12.1 |
  | 23 | 285474 | fife |
  | 24 | 280451 | tengine |
  | 25 | 274510 | nginx/1.13.4 |
  | 26 | 274371 | microsoft-iis/10.0 |
  | 27 | 271034 | apache/2.4.7 (ubuntu) |
  | 28 | 270736 | nginx/1.6.2 |
  | 29 | 259547 | openresty |
  | 30 | 254803 | nginx/1.8.0 |
  | 31 | 251104 | apache/2 |
  | 32 | 233983 | microsoft-iis/8.0 |
  | 33 | 214911 | nginx/1.10.1 |
  | 34 | 202578 | apache/2.4.10 (debian) |
  | 35 | 196628 | apache/2.4.18 (ubuntu) |
  | 36 | 195562 | nginx/1.10.3 (ubuntu) |
  | 37 | 192706 | ats |
  | 38 | 192638 | proxygen-bolt |
  | 39 | 192266 | nginx/1.10.3 |
  | 40 | 191217 | microsoft-iis/6.0 |
  | 41 | 190284 | oxgw/11.174.1 |
  | 42 | 185092 | nginx/1.4.6 (ubuntu) |
  | 43 | 171113 | tsa_a |
  | 44 | 151603 | gse |
  | 45 | 151177 | apache/2.2.22 (debian) |
  | 46 | 118974 | youtube frontend proxy |
  | 47 | 113280 | microsoft-iis/7.0 |
  | 48 | 113056 | apache/2.2.24 (unix) mod_ssl/2.2.24 openssl/1.0.1e-fips mod_fastcgi/2.4.6 |
  | 49 | 112569 | google tag manager (scaffolding) |
  | 50 | 112368 | server |
  | 51 | 109926 | adclick_server |
  | 52 | 108713 | nginx-reuseport/1.13.4 |
  | 53 | 100626 | rubicon project |
  | 54 | 96278 | nginx/1.2.1 |
  | 55 | 80083 | adaptv/1.0 |
  | 56 | 79206 | keycdn-engine |
  | 57 | 78922 | cowboy |
  | 58 | 76994 | apache/2.4.29 |
  | 59 | 69297 | pws/8.3.1.0.4 |
  | 60 | 66702 | apache/2.2.22 (ubuntu) |
  | 61 | 65890 | apache/2.2.3 (centos) |
  | 62 | 65597 | cdn77-turbo |
  | 63 | 60358 | jetty(9.4.6.v20170531) |
  | 64 | 59865 | varnish |
  | 65 | 57010 | yunjiasu-nginx |
  | 66 | 56478 | safe |
  | 67 | 56328 | mafe |
  | 68 | 56299 | apache/2.2.15 (red hat) |
  | 69 | 56196 | paintfe |
  | 70 | 55656 | nginx/1.0.15 |
  | 71 | 52362 | jetty(8.1.13.v20130916) |
  | 72 | 51960 | uploadserver |
  | 73 | 50897 | aawebserver |
  | 74 | 50829 | qs |
  | 75 | 45276 | cloudinary |
  | 76 | 41882 | proxygen |
  | 77 | 41058 | nginx/1.11.3 |
  | 78 | 40283 | google frontend |
  | 79 | 39659 | apache/2.2.16 (debian) |
  | 80 | 39239 | akka-http/2.4.10 |
  | 81 | 39065 | 0w/0.8c |
  | 82 | 38817 | nginx/1.1.19 |
  | 83 | 38118 | apache/2.4 |
  | 84 | 37951 | apache/2.4.29 (cpanel) openssl/1.0.2m mod_bwlimited/1.4 |
  | 85 | 37520 | nginx/1.9.12 |
  | 86 | 37396 | gvs 1.0 |
  | 87 | 36353 | akamai image manager |
  | 88 | 36278 | lighttpd/1.4.33 |
  | 89 | 35457 | ribs2.0 |
  | 90 | 34183 | windows-azure-blob/1.0 microsoft-httpapi/2.0 |
  | 91 | 34132 | nginx/1.10.0 (ubuntu) |
  | 92 | 32782 | apache/2.4.27 |
  | 93 | 32710 | nginx/1.13.5 |
  | 94 | 32693 | apache/2.2.22 |
  | 95 | 31836 | apache/2.4.25 (debian) |
  | 96 | 31627 | nginx/1.13.6 |
  | 97 | 31340 | nginx/1.13.3 |
  | 98 | 31024 | jetty(9.0.6.v20130930) |
  | 99 | 30849 | jsp3/2.0.14 |
  | 100 | 30641 | jumble_frontend_server |

* Query used:

  ```sql
  select count(requestid) as number_of_requests, lower(resp_server) as server_header_value
  from [httparchive:runs.latest_requests] 
  group by server_header_value
  order by number_of_requests desc
  ```

</details>

**Comment by molant** [comment]
Except jetty, all the other version schemas are of type `/x.y.z`.

IMO we should go for a black list were we have a regex for versions plus maybe some other keywords (`php`, `express`,  etc.).
