### ISSUE TITLE
Publish rules as standalone npm packages

### ISSUE THREAD

**Issue by alrra** [sonarwhal/sonarwhal#748]
- [x] Refactor code to make this possible.
- [x] Publish rules as standalone `npm` packages.
- [x] Update infrastructure and release script.
- [x] Update the wizard logic that displays the rules that can be installed. I'm thinking about doing an npm search and all rules that are under `@sonarwhal` should be in there
- [x] Delete the logic for core/no-core rules
- [x] Update the skeleton of the rules to include `nyc`

**Comment by molant** [comment]
For context, some of the reasons why we want to do this:

* shorter and more reliable builds
* update rules without having to update sonarwhal
* be prepared to install rules on demand on first run

**Comment by molant** [comment]
Some other things that we need to do in here:

* [ ] Update the wizard logic that displays the rules that can be installed. I'm thinking about doing an npm search and all rules that are under `@sonarwhal` should be in there
* [ ] Delete the logic for core/no-core rules
* [ ] Probably something else?

**Comment by alrra** [comment]
Note: We are working on this in the [`fix-748` branch](https://github.com/sonarwhal/sonarwhal/tree/fix-748).

**Comment by molant** [comment]
Making a list to know what rules are passing or not with the current project. The ones that aren't checked and don't have a comment I haven't tested them yet.

* [ ] amp-validator: has an issue installing on windows in the post-install script
* [X] apple-touch-icons
* [X] axe
* [X] content-type
* [X] disown-opener
* [X] highest-available-document-mode
* [ ] html-checker: 2 failing tests with chrome
* [X] http-cache
* [X] http-compression: 63 skipped tests (chrome is ignored)
* [X] image-optimization-cloudinary: 6 skipped tests (guess chrome is ignored)
* [X] manifest-app-name
* [X] manifest-exists
* [X] manifest-file-extension
* [ ] manifest-is-valid
* [ ] meta-charset-utf-8
* [ ] meta-viewport
* [ ] no-disallowed-headers
* [ ] no-friendly-error-pages
* [ ] no-html-only-headers
* [ ] no-http-redirects
* [ ] no-protocol-relative-urls
* [ ] no-vulnerable-javascript-libraries
* [ ] ssllabs
* [ ] strict-transport-security
* [ ] validate-set-cookie-header
* [ ] x-content-type-options

**Comment by molant** [comment]
Forgot to mention the results above are with my current work. I had to fix something on jsdom when accessing the attributes so you might not get the same until my work is merged.

**Comment by molant** [comment]
All rules except the `amp` one are working now and pushed into the `fix-748` branch.
There are some that need more test coverage like `strict-transport-security`. Will work on that next probably.

**Comment by alrra** [comment]
This issue is kinda done, further improvements will be address separately.
