### ISSUE TITLE
Button Clicks are not working for Sonarwhal Reports to open details about the issues in the reports

### ISSUE THREAD

**Issue by 0test2018** [sonarwhal/sonarwhal#762]
Please tell us about your:

## Environment

* __`sonarwhal` version:__
* __`Node.js` version:__
* __`npm` version:__

## `sonarwhal` configuration

<details>
<summary>sonarwhal’s configuration</summary>

```js



```

</details>

## URL for which `sonarwhal` failed

* __URL:__

## Output

Please include the raw output generated by `sonarwhal`, or if possible,
the raw output from running `sonarwhal` in debug mode: `sonarwhal --debug <URL>`.

<details>
<summary>sonarwhal’s raw output</summary>

```text



```

</details>

**Comment by alrra** [comment]
@0test2018 [I've moved this issue in the website repository](https://github.com/sonarwhal/sonarwhal.com/issues/356). Thanks!
