### ISSUE TITLE
Reorganize contributor guide

### ISSUE THREAD

**Issue by molant** [sonarwhal/sonarwhal#781]
Right now the topics aren't clear, the information is a bit scattered, and it could use some clean up.

**Comment by molant** [comment]
This is how it's starting to look like:
![image](https://user-images.githubusercontent.com/606594/35455873-7e79adf4-0288-11e8-961a-9e5063f7fad0.png)

I have to change the names of the `developing` sections (or that section).
I'd like to split the content of rules, which is becoming pretty big into subsections but I'm not sure where to put them yet

**Comment by alrra** [comment]
Feedback welcomed on: #784.
