### ISSUE TITLE
Incorrect recommendation for JavaScript content-type header

### ISSUE THREAD

**Issue by paulschreiber** [sonarwhal/sonarwhal#787]
Sonarwhal is providing an incorrect content-type recommendation for JavaScript.

It states:
```
'content-type' header should have media type 'text/javascript'
(not 'application/x-javascript')
```

The value should be `application/javascript`. See [RFC 4329](http://www.rfc-editor.org/rfc/rfc4329.txt)

**Comment by alrra** [comment]
@paulschreiber See: #568.

**Comment by paulschreiber** [comment]
@alrra #568 is closed, and makes an incorrect recommendation (text/javascript). The IETF document you referred to is still a draft.

**Comment by alrra** [comment]
@paulschreiber See: https://github.com/sonarwhal/sonarwhal/issues/568#issuecomment-339945844 & [HTML spec](https://github.com/whatwg/html/pull/3096) .

**Comment by alrra** [comment]
> HTML spec

See also: https://html.spec.whatwg.org/multipage/infrastructure.html#dependencies

![](https://user-images.githubusercontent.com/1223565/35583973-66aea12a-05a8-11e8-91ab-8b1a218bcf7d.png)
