### ISSUE TITLE
GitHub edit links in user guide are broken (404)

### ISSUE THREAD

**Issue by paulschreiber** [sonarwhal/sonarwhal#788]
GitHub edit links in the Sonarwhal user guide are broken and lead to 404s:

Example page:
https://sonarwhal.com/docs/user-guide/rules/content-type/

Edit URL provided:
https://github.com/sonarwhal/sonarwhal/blob/master/docs/user-guide/rules/content-type/index.md

**Comment by alrra** [comment]
@paulschreiber Can you open this issue in the [site repository](https://github.com/sonarwhal/sonarwhal.com)? Thanks!

**Comment by molant** [comment]
@alrra I opened in https://github.com/sonarwhal/sonarwhal.com/issues/375

**Comment by alrra** [comment]
@molant :+1:

---

@paulschreiber Thanks for letting us know about this issue!

**Comment by alrra** [comment]
This is now [fixed](https://github.com/sonarwhal/sonarwhal.com/issues/375)!  🎉
