### ISSUE TITLE
using Sonarwhal with Docker

### ISSUE THREAD

**Issue by SeriyVol4ishe** [sonarwhal/sonarwhal#799]
How can I configure Sonarwhal in docker container? 
Is here some example of '.sonarwhalrc' and where is its location (to put completed file with `COPY /.sonarwhalrc /destination`)?

**Comment by sarvaje** [comment]
Hi @SeriyVol4ishe,

Can you explain a little bit more your scenario? And the result/error you are getting right now?

I'm thinking about sonarwhal with docker and I have a couple of ideas, but I would like to know your problem first :)

Thanks!

**Comment by sarvaje** [comment]
@SeriyVol4ishe I have created #800 just in case you have some another idea. Thanks!

**Comment by alrra** [comment]
Closing in favor of #800.
