### ISSUE TITLE
Update Twitter header image

### ISSUE THREAD

**Issue by alrra** [sonarwhal/sonarwhal#810]
It still says `sonar`:

<img width="334" src="https://user-images.githubusercontent.com/1223565/36067985-04d6f1e8-0e7f-11e8-848f-df3b89bc7fb9.png">

**Comment by ststimac** [comment]
This has been updated.

<img width="1426" alt="screen shot 2018-02-12 at 10 37 37 am" src="https://user-images.githubusercontent.com/18073131/36113210-f06741dc-0fe0-11e8-801b-e141cc3ac400.png">
