### ISSUE TITLE
Generate a permalink (report formatted in HTML) through the JSON generated by Sonarwhal installed on my PC?

### ISSUE THREAD

**Issue by ricardogaldino** [sonarwhal/sonarwhal#812]
Hello,

Is it possible for me to generate a permalink (report formatted in HTML) through the JSON generated by Sonarwhal installed on my PC?

I would like to take advantage of the report (already formatted in HTML) using JSON generated by Sonarwhal.

Is there an Import and Export scan feature that manages the permalink (online)?

**Comment by molant** [comment]
Hi @ricardogaldino,
sorry it took me so long to answer. Currently there's no way for you to send a JSON to the online service. What we are going to do in the near future is to add an HTML formatter (#284) that should generate the same output as the website.

In the meantime you can maybe use the [Excel formatter](https://sonarwhal.com/docs/user-guide/concepts/formatters/#list-of-official-formatters) (it's the last one in that list).

I'm closing this in favor of #284.

Thanks!
