### ISSUE TITLE
Documentation URLs are returning 404 on site

### ISSUE THREAD

**Issue by adammarton** [sonarwhal/sonarwhal#836]
Documentation pages are linked like https://sonarwhal.com/docs/user-guide/rules/content-type/ while https://sonarwhal.com/docs/user-guide/rules/rule-content-type/ is the correct URL. It seems all URLs are affected.

**Comment by alrra** [comment]
@adammarton Thanks for reporting this, [I've opened this issue in your site repository](https://github.com/sonarwhal/sonarwhal.com/issues/397)!

**Comment by alrra** [comment]
@adammarton This should be now fixed. Thanks again for opening this issue!
