### ISSUE TITLE
Add how to override the `Server` Header in Documentation

### ISSUE THREAD

**Issue by qzhou1607** [sonarwhal/sonarwhal#846]
Because an error of ` 'Server' header value contains more than the server name` was reported by `no-disallowed-headers`. I was looking for ways to override the `Server` Header for a website hosted in IIS, and it took me some time. It could be useful to add the solutions to override the header in the documentation of that rule.

https://stackoverflow.com/a/12615970

**Comment by molant** [comment]
This was don in https://github.com/sonarwhal/sonarwhal/commit/b67ef431da269daf93a7173e6051991e8478deec
