### ISSUE TITLE
Rule sslabs check that endpoints exists

### ISSUE THREAD

**Issue by sarvaje** [sonarwhal/sonarwhal#848]
Sometimes, we get this error in the online scanner:

```
TypeError: Cannot read property 'endpoints' of undefined
online-service_worker-service.17.0jzbgue26ak8@swarm-worker000002    |     at end (/app/node_modules/sonarwhal/dist/src/lib/rules/ssllabs/ssllabs.js:94:23)
online-service_worker-service.17.0jzbgue26ak8@swarm-worker000002    |     at <anonymous>
online-service_worker-service.17.0jzbgue26ak8@swarm-worker000002    |     at process._tickCallback (internal/process/next_tick.js:160:7)
```

We should check if the property `endpoints` exists or not (maybe report a warning if it doesn't exists?)

**Comment by molant** [comment]
We've had a similar error with `html-checker`. Need to find a good solution to not break when we use a third party service and document it

**Comment by molant** [comment]
Actually the problem here is that `host` doesn't exist
