### ISSUE TITLE
Update `--new-rule` process

### ISSUE THREAD

**Issue by alrra** [sonarwhal/sonarwhal#857]
Update `--new-rule` process to:

- [x] Add a `.npmrc` file containing  `package-lock=false` (see also: https://github.com/sonarwhal/sonarwhal/commit/8638385ab5070927bb05e0483dcd5368f0b41d1d)
- [x] Have `lint:md` script from `package.json` ignore `CHANGELOG.md` files (see also: https://github.com/sonarwhal/sonarwhal/commit/dd1b3710d73b5c0e60780bde02d8a4a4a0310d0d)
- [x] Update dependencies to latest versions

**Comment by molant** [comment]
* [ ] Update dependencies to latest versions
