### ISSUE TITLE
Http://att.net problems 

### ISSUE THREAD

**Issue by Survivedabuse73** [sonarwhal/sonarwhal#882]
[Lifecycle (2).pdf](https://github.com/sonarwhal/sonarwhal/files/1809575/Lifecycle.2.pdf)

Please tell us about your:

## Environment

* __`sonarwhal` version:__
* __`Node.js` version:__
* __`npm` version:__

## `sonarwhal` configuration

<details>
<summary>sonarwhal’s configuration</summary>

```js



```

</details>

## URL for which `sonarwhal` failed

* __URL:__

## Output

Please include the raw output generated by `sonarwhal`, or if possible,
the raw output from running `sonarwhal` in debug mode: `sonarwhal --debug <URL>`.

<details>
<summary>sonarwhal’s raw output</summary>

```text



```

</details>

**Comment by molant** [comment]
Did a quick test and I'm getting results with the online version: https://sonarwhal.com/scanner/c6b8da39-7a8f-4836-a627-da99d4ed1fa1

If there's something wrong please fill the template on your first comment with the requested information and let us know so we can reopen and investigate.

Thanks!

**Comment by Survivedabuse73** [comment]
Always have issue with them

**Comment by molant** [comment]
@Survivedabuse73 unless you fill the initial template with information about the version you are using, configuration, etc. there's not a lot we can do to help you
