### ISSUE TITLE
Review CLI help menu

### ISSUE THREAD

**Issue by molant** [sonarwhal/sonarwhal#886]
There are a few things that are outdated in the CLI help menu (`sonarwhal -h`). We should make sure the information is up to date:

![image](https://user-images.githubusercontent.com/606594/37417734-39995788-276e-11e8-840c-e749ef3b08a4.png)

Some examples: 

* [x] I don't think we use `stylish` as default anymore
* [x] `-o` don't think it works
* [x] `--remove-rule` was removed IIRC
* [x] `-f` don't think we ever implemented this (but could definitely do it in a separate issue)

**Comment by alrra** [comment]
> --remove-rule was removed IIRC

Yes, see https://github.com/sonarwhal/sonarwhal/commit/03b798b2411a.
