### ISSUE TITLE
Add rule to check for mixed content

### ISSUE THREAD

**Issue by alrra** [sonarwhal/sonarwhal#887]
See also: https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content

**Comment by sarvaje** [comment]
There is two types of Mixed content. Should we show a different message depending on the type?

**Comment by sarvaje** [comment]
For more info about the Mixed content see: https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content
or 
https://developers.google.com/web/fundamentals/security/prevent-mixed-content/what-is-mixed-content

**Comment by molant** [comment]
IMO one message should be enough. Everything should be on https.

**Comment by kshyju** [comment]
Has anyone started working on this ?

**Comment by molant** [comment]
Yes, there's a PR for it. You can help with the code review if you want 😊

**Comment by alrra** [comment]
> Has anyone started working on this ?

See: https://github.com/sonarwhal/sonarwhal/pull/1010
