### ISSUE TITLE
allow the user set the formatter in the cli

### ISSUE THREAD

**Issue by sarvaje** [sonarwhal/sonarwhal#888]
Related with #886

**Comment by kshyju** [comment]
Has anyone started working on this ? If not, i would like to give it a try,

**Comment by molant** [comment]
Go for it @kshyju

Let us know if you need anything!

**Comment by kshyju** [comment]
I am thinking something like this

    sonarwhal https://www.google.com --formatter excel
and

    sonarwhal https://www.google.com -f  excel

Which will overwrite the existing `formatters` property with this new value.

Question : Should it support multiple formatters (comma seperated `excel,summary`) ?

**Comment by molant** [comment]
`--formatter` and `-f` sound good to me. Support for multiple formatters would be cool tool.

One thing to keep in mind is that doing something like:

```bash
sonarwhal https://example.com -f wrongFormatter
```

should fail saying the resource `wrongFormatter` is not found (same as if it were in the `.sonarwhalrc` file.

I guess you'll have to do the replacement of formatters somewhere [around here in `analyze.ts`](https://github.com/sonarwhal/sonarwhal/blob/9d159a011c21ce01f39f80903c9319ad2046fe6f/packages/sonarwhal/src/lib/cli/analyze.ts#L158)

**Comment by kshyju** [comment]
Currently, specifying the wrong formatter in the config file is not yielding in an error!
Config 
<img width="398" alt="screen shot 2018-04-19 at 9 46 15 pm" src="https://user-images.githubusercontent.com/144469/39031091-1d889f8a-441b-11e8-82ca-e6656b2970fe.png">
Result
<img width="741" alt="screen shot 2018-04-19 at 9 44 58 pm" src="https://user-images.githubusercontent.com/144469/39031106-31822718-441b-11e8-96c3-f84d8efd0fd3.png">

But it works for the connectors (It throws the error)
Config
<img width="257" alt="screen shot 2018-04-19 at 9 43 08 pm" src="https://user-images.githubusercontent.com/144469/39031113-401a5ade-441b-11e8-99c6-f0daefa0863d.png">
Result
<img width="744" alt="screen shot 2018-04-19 at 9 44 09 pm" src="https://user-images.githubusercontent.com/144469/39031119-496acc36-441b-11e8-92f1-6297b02d2f18.png">

I have the other changes (support for CLI option) almost ready.

**Comment by molant** [comment]
Actually the `formatter` behavior is the correct one (ask to try to install it).
We need to figure out why `connector`s throw an exception. I'll open an issue for that.

Thanks!

**Comment by kshyju** [comment]
Thanks! Can you give me some leads on how to run unit tests on a specific file/module (instead of running all the tests under `packages\sonarwhal` ). My primary code change is in `packages/sonarwhal/src/lib/cli/analyze.ts` I wonder there is a way to run tests only for the cli.

**Comment by molant** [comment]
Yes, if you are using vscode you can have the following configuration:

```js
{
            "type": "node",
            "request": "launch",
            "name": "Test file",
            "program": "node_modules/ava/profile.js",
            "sourceMaps": true,
            "args": [
                "${workspaceFolder}/packages/sonarwhal/dist/tests/PATHTOYOURFILE.js"
            ],
            "cwd": "${workspaceFolder}/packages/sonarwhal"
        }
```

or if you just use the command line then from the root of the project

```bash
node_modules/ava/profile.js packages/sonarwhal/dist/tests/PATHTOYOURFILE.js
```

I recommend to run `yarn watch:ts` from `/packages/sonarwhal/` in another window. I've forgot it a few times and run crazy trying to figure out why my changes weren't working.
