### ISSUE TITLE
ATT email is not working

### ISSUE THREAD

**Issue by Survivedabuse73** [sonarwhal/sonarwhal#898]
Please tell us about your:

## Environment

* __`sonarwhal` version:__
* __`Node.js` version:__
* __`npm` version:__

## `sonarwhal` configuration

<details>
<summary>sonarwhal’s configuration</summary>

```js



```

</details>

## URL for which `sonarwhal` failed

* __URL:__

## Output

Please include the raw output generated by `sonarwhal`, or if possible,
the raw output from running `sonarwhal` in debug mode: `sonarwhal --debug <URL>`.

<details>
<summary>sonarwhal’s raw output</summary>

```text



```

</details>

**Comment by alrra** [comment]
@Survivedabuse73 As [previously specified](https://github.com/sonarwhal/sonarwhal/issues/882#issuecomment-373245703), please provide more information if you want us to help you. Thanks!
