### ISSUE TITLE
Issue extending `web-recommended` and configuring `http-compressions`

### ISSUE THREAD

**Issue by molant** [sonarwhal/sonarwhal#905]
Original report by @jgarber623:

This configuration works, but doesn't include any rule customization:

```json
{
  "extends": [
    "web-recommended"
  ],
  "formatters": [
    "codeframe"
  ],
  "ignoredUrls": [
    {
      "domain": ".*\\.googleapis\\.com/.*",
      "rules": ["*"]
    }
  ]
}
```

This configuration does _not_ work:

```json
{
  "extends": [
    "web-recommended"
  ],
  "formatters": [
    "codeframe"
  ],
  "rules": {
    "http-compression": ["warning", {
      "html": {
        "brotli": false
      }
    }]
  },
  "ignoredUrls": [
    {
      "domain": ".*\\.googleapis\\.com/.*",
      "rules": ["*"]
    }
  ]
}
```

The error message shown is "Invalid rule configuration in .sonarwhalrc: http-compression."

My goal is to silence errors/warnings about using Brotli and Zopfli compression.

**Comment by molant** [comment]
The following works:

```json
  "extends": [
    "web-recommended"
  ],
  "formatters": [
    "codeframe"
  ],
  "rules": {
    "http-compression": "off"
  },
  "ignoredUrls": [
    {
      "domain": ".*\\.googleapis\\.com/.*",
      "rules": ["*"]
    }
  ]
}
```

so it looks like a problem when merging the rule configurations options with the `extends` part.

**Comment by molant** [comment]
I've created #907 to fix this issue. If you don't want to wait until things are merged and published on npm you can change `html` with `target` in your configuration and it should work.

**Comment by alrra** [comment]
@jgarber623 We published a new version of the [`http-compression`](https://www.npmjs.com/package/@sonarwhal/rule-http-compression) rule. So, the easiest way to get it is to just do a `npm i @sonarwhal/configuration-web-recommended`. 

Thanks again for taking the time to let us know!

**Comment by jgarber623** [comment]
Thanks, @molant and @alrra! Those updates did the trick. 

For future travelers, my updated config works great and now looks like:

```json
{
  "extends": [
    "web-recommended"
  ],
  "formatters": [
    "codeframe"
  ],
  "rules": {
    "http-compression": ["warning", {
      "html": {
        "brotli": false,
        "zopfli": false
      },
      "resource": {
        "brotli": false,
        "zopfli": false
      }
    }]
  },
  "ignoredUrls": [
    {
      "domain": ".*\\.googleapis\\.com/.*",
      "rules": ["*"]
    }
  ]
}
```
