### ISSUE TITLE
Normalize TypeScript configuration on parser?

### ISSUE THREAD

**Issue by molant** [sonarwhal/sonarwhal#906]
I think it will be interesting for the parser to set the defaults of properties that are not set explicitly in the `tsconfig.json` and also normalize values when several are possible with the same out put.
 E.g.:

- If `target` is not specified, the value will be `ES3`
- `ES6` is the same as using `ES2015` on `target`
- `traceResolution` default is `false`
- ...

Doing this will make things easier to handle at the rule level. Also, if one default changes we will only have to update one place: the parser.

This could apply to other parsers as well like the Babel one (haven't look into it yet).

@sonarwhal/core what do you think?

**Comment by sarvaje** [comment]
Do you mean the configuration we are parsing?
I don't get why we want to normalize anything, I mean, sonarwhal should validate/analyze what the user has in his project, we shouldn't normalize it. If a rule is checking the target property, maybe then the rule can normalize it (or not).

**Comment by molant** [comment]
There are a few benefits that come to my mind:

* No need to check if a property exists because we know that it will have the default value if the user hasn't declared it
* No need to check for multiple options for the same property (ES6 and ES2015 are the same, we could just send ES2015)
* If multiple rules need to access those properties, the code is going to be duplicated and will not give any value
* If a default changes in TypeScript XXX, we will need to update the code in multiple rules instead of just the parser

**Comment by molant** [comment]
Also, because values can be upper case or lower case we have to check for those also in the rules... By normalizing we know that they should be all upper case or lower case.

**Comment by sarvaje** [comment]
> No need to check if a property exists because we know that it will have the default value if the user hasn't declared it

But the user hasn't declared the value.

What if I want to have a rule that check if the user has declared a value for target (or another property), If I normalize the config adding default values, I can't have a rule to check that.

> Also, because values can be upper case or lower case we have to check for those also in the rules... By normalizing we know that they should be all upper case or lower case.

I'm ok with this case, we can normalize the case of the properties, but I don't think we should modify what the user has in his configuration.

**Comment by molant** [comment]
> What if I want to have a rule that check if the user has declared a value for target (or another property), If I normalize the config adding default values, I can't have a rule to check that.

Fair enough. Maybe we should send the user config and the applied config in the event and then the rule can check whatever it needs. We might actually have to do something like that if we use `extends` and want/need the final config.

Also, I really think we should centralized the default values in just one place instead of repeating the same code everywhere where we need to access the property.
Right now to access the `target` I need to do something like  `config && config.compilerOptions && config.compilerOptions.target` which is really ugly (and can be even messier if the type is something like a Boolean or number 0). If I know that property is always going to exist because of the defaults, the code readability is going to improve a lot.
Also, if for whatever reason a default gets updated we just need to update the parser and not all the rules where it's usd, so getting up to date is a lot easier.

**Comment by sarvaje** [comment]
What about instead of normalize by default, the parser has a static method `normalize` that you can use it in wherever and whenever you need it?

**Comment by molant** [comment]
I think I prefer the option of sending the user's config object (what we do right now) and the normalized/applied configuration in the same event. Having the static method means that the rules will have a hard dependency on the rule and will have to require it. Also we will be doing the work multiple times if several rules have to normalize the content.

**Comment by sarvaje** [comment]
@molant I think we can close this. We are currently sending the original configuration the user has in his config file, and also the configuration with the defaults values that the schema validator returns.

**Comment by molant** [comment]
I'll probably need to update my PR :)
