### ISSUE TITLE
Improve `rule-no-bom`

### ISSUE THREAD

**Issue by alrra** [sonarwhal/sonarwhal#923]
- [x] Make it work with the local connector.
- [x] For consistency, maybe change the error message from `Text based files shouldn't start...`  to `Resource shouldn't start...`

**Comment by molant** [comment]
For the local connector:

* I believe the current `local` connector doesn't support `fetchContent` (although it should be easy to add as it will be just a `fs.readFile`)
* I'm thinking about checking for the BOM directly with the data that comes in the event and if it's not present then use the `fetchContent` code we have right now.
* Benefits: If the BOM is present, it will be detected sooner in `local` and `jsdom` and we will save an extra request.

Another approach will be to add a property or something to the connector or context that tells if the data might have been changed and then do the manual request and thus doing less code.

@sarvaje any thoughts about this?

**Comment by sarvaje** [comment]
this should be easy, we already have a private method `fetch`. I think that we just need to change the name to `fetchContent` and make it public

**Comment by sarvaje** [comment]
we cannot just rename, but it should be easy, I'm going to start working on this.

**Comment by sarvaje** [comment]
>  For consistency, maybe change the error message from Text based files shouldn't start... to Resource shouldn't start...

Should I change this message?, because the rule just apply to text files.

**Comment by molant** [comment]
Maybe to `Text based resources shouldn't start...` ?
