### ISSUE TITLE
Standarize parsers events

### ISSUE THREAD

**Issue by sarvaje** [sonarwhal/sonarwhal#930]
It should be something like:

* Parse is done: `parse::<parserName>::end`
* Errors: Should be prefixed with `parse::<parserName>::error` following with the error type. e.g.:
    * JSON error: `parse::<parserName>::error::json`
    * Schema error: `parse::<parserName>::error::schema`
    * Local file not found: `parse::<parserName>::error::not-found`
    * File not specified in web site: `parse::<parserName>::error::not-specified`
    * File can't be downloaded or generate a 404: `parse::<parserName>::error::not-accessible`

---

Note: `error` events will depend on the parser.

**Comment by alrra** [comment]
Note: `error` events will depend on the parser.
