### ISSUE TITLE
Automatically update rule list

### ISSUE THREAD

**Issue by alrra** [sonarwhal/sonarwhal#955]
We should have a script that automatically generates the content from the [`docs/user-guide/rules/index.md`](https://github.com/sonarwhal/sonarwhal/blob/562d6fdcdb87cf9a10e009b6ec88dc33c0135885/packages/sonarwhal/docs/user-guide/rules/index.md) file.

**Comment by molant** [comment]
The online version is now updated automatically. This was done via https://github.com/sonarwhal/sonarwhal.com/commit/6e967f65ba6b92577cdf4d12446ef7ca5959ae5c
