### ISSUE TITLE
`fetch::end::html` is received also for non-HTML targets

### ISSUE THREAD

**Issue by alrra** [sonarwhal/sonarwhal#982]
The connectors assume that the target is HTML, and that is not always the case.

e.g.: Even thought a rule subscribes to [`fetch::end::html`](https://github.com/sonarwhal/sonarwhal/blob/db6337c7a4cc368ef2ef9c6477b80b34eaafc0bf/packages/rule-meta-charset-utf-8/src/rule.ts#L167), it still has to [check if what it receives is a HTML Document](https://github.com/sonarwhal/sonarwhal/blob/db6337c7a4cc368ef2ef9c6477b80b34eaafc0bf/packages/rule-meta-charset-utf-8/src/rule.ts#L72-L73).

**Comment by sarvaje** [comment]
I'm changing my mind, I'm just going to check the type :)

**Comment by alrra** [comment]
Fixed in https://github.com/sonarwhal/sonarwhal/commit/b7334521b528ffbc9703548f497a6a2ee1c9a550.
