### ISSUE TITLE
Error: schema is invalid

### ISSUE THREAD

**Issue by chrisguttandin** [sonarwhal/sonarwhal#993]
When using an array as configuration for rules like content-type, disown-opener, highest-available-document-mode, ... the parsing of the configuration fails. I figured out that this is caused by the `schema` property of their meta object. It always contains a line like this: `type: ['object', null]`. When changed to `type: ['object', 'null']` all seems to work fine again.

Please tell us about your:

## Environment

* __`sonarwhal` version:__ 1.5.0
* __`Node.js` version:__ 9.11.1
* __`npm` version:__ 5.8.0

## `sonarwhal` configuration

<details>
<summary>sonarwhal’s configuration</summary>

```js
// ...
"content-type": ["error", {
    ".*\\.js": "application/javascript; charset=utf-8"
}],
// ...
```

</details>

## URL for which `sonarwhal` failed

* __URL:__ any

## Output

Please include the raw output generated by `sonarwhal`, or if possible,
the raw output from running `sonarwhal` in debug mode: `sonarwhal --debug <URL>`.

<details>
<summary>sonarwhal’s raw output</summary>

```text
Error: schema is invalid: data.type should be equal to one of the allowed values, data.type[1] should be equal to one of the allowed values, data.type should match some schema in anyOf


```

</details>

**Comment by alrra** [comment]
@chrisguttandin Thanks for opening this issue and letting us know about this! 

----

> When changed to type: ['object', 'null'] all seems to work fine again.

Yes, it should be `'null'`,  not `null`.

Ref: 

* http://json-schema.org/latest/json-schema-core.html#rfc.section.4.2.1
* https://spacetelescope.github.io/understanding-json-schema/reference/null.html

**Comment by alrra** [comment]
@chrisguttandin Things should be fixed and published! 🎉

**Comment by chrisguttandin** [comment]
Thanks @alrra for the quick response.
